cc_library(
  name = "io_file",
  srcs = [
        "file_writer.cc",
        "file_reader.cc",
    ],
    hdrs = [
        "file_writer.h",
        "file_reader.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)